@BasicAuthHandler_HostAddress = http://localhost:443
@TokenAuth = R2VuZXJpY05hbWU6VXNlcktleTEyMzQ=

GET {{BasicAuthHandler_HostAddress}}/BasicAuth
Accept: application/json
Authorization: Basic {{TokenAuth}}

###
